//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string Specialnost { get; set; }
        public decimal Stoimost_Priema { get; set; }
        public int Procent_otcislenia_na_zp { get; set; }
    }
}
